version: "2"

services:

  jenkins-master:
    build:
      context: ./master
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    ports:
      - "8080:8080"
      # JNLP-based Jenkins agents TCP port (Configure Global Security)
      - "50000:50000"
    volumes:
      # - jenkins-data:/var/jenkins_home
      - ./backup:/var/jenkins_home
      # Jenkins comm with Docker daemon used for launching Docker agents
      # - /var/run/docker.sock:/var/run/docker.sock

  jenkins-agent:
    build:
      context: ./agents
      dockerfile: Dockerfile-ubuntu
    ports:
      - "22:22"

  # Default user: admin, password: password
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:4.15.0
    ports:
      - "8081:8081"
    volumes:
    - ./artifactory/data:/var/opt/jfrog/artifactory/data
    - ./artifactory/logs:/var/opt/jfrog/artifactory/logs
    - ./artifactory/etc:/var/opt/jfrog/artifactory/etc


  sonarqube:
    image: sonarqube:lts
    ports:
      - "9000:9000"

volumes:
  jenkins-data:



